---
title: "tidytuesday"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidytuesdayR)
library(tidyverse)


tt <- tidytuesdayR::tt_load('2021-06-22')

parks <- tt$parks 

parks %>% 
  group_by(year)%>%
  summarise(n_city=n_distinct(city))%>%
  ggplot(aes(year,n_city))+geom_col()+
  labs(x = 'Year',
       y = 'No of cities',
       title = 'No of cities surveryed year wise')


make_boxplot <- function(tbl,var) {
  
  tbl %>% 
    ggplot(aes(factor(year),{{var}}))+geom_boxplot()+
    labs(x = 'Year',
         y= colnames(tbl%>%select({{var}})))
}


parks %>% 
  make_boxplot(.,med_park_size_data)


parks %>% 
  mutate(park_pct_city_data=parse_number(park_pct_city_data)/100)%>%
  make_boxplot(.,park_pct_city_data)

parks %>% 
  mutate(pct_near_park_data=parse_number(pct_near_park_data)/100)%>%
  make_boxplot(.,pct_near_park_data)

parks %>% 
  mutate(spend_per_resident_data=parse_number(spend_per_resident_data))%>%
  make_boxplot(.,spend_per_resident_data)


parks %>% 
  make_boxplot(.,basketball_data)

parks %>% 
  mutate(total_points_new = rowSums(select(.,contains('points')),na.rm = T))%>%
  make_boxplot(total_points_new)



```
