---
title: "tidymodels_drwho_ratings"
output: html_document
date: "2023-11-28"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidytuesdayR)
library(tidyverse)
library(tidymodels)
library(janitor)


tuesdata <- tidytuesdayR::tt_load('2023-11-28')

episodes <- tuesdata$drwho_episodes %>% clean_names()
directors <- tuesdata$drwho_directors %>% clean_names()
writers <- tuesdata$drwho_writers %>% clean_names()

```

### Lets do some EDA

```{r}

episodes %>% 
  glimpse()

episodes %>% 
  skimr::skim()


episodes_joined <- episodes %>% 
  left_join(.,directors,
            by = c('story_number'))%>%
  left_join(.,writers,
            by = c('story_number'))


episodes_joined %>% 
  count(director)

episodes_joined%>%
  ggplot(aes(uk_viewers))+geom_histogram()

```


### Build model
1. Clean data, define recipe and model spec


```{r}
episodes_clean <-
episodes_joined %>% 
  select(uk_viewers,rating,duration)%>%
  drop_na()


episodes_clean %>% 
  skimr::skim()

episode_split <- initial_split(episodes_clean)
episode_train <- training(episode_split)
episode_test <- testing(episode_split)

episode_train %>% 
  view()

episode_folds <- vfold_cv(episode_train)


episode_rec <- recipe(rating ~ ., data = episode_train)%>%
  step_dummy(all_nominal_predictors())%>%
  step_zv(all_nominal_predictors())%>%
  step_normalize(all_numeric_predictors())


episode_rec %>% prep()%>% bake(new_data = NULL)%>%
  view()



episode_spec <-
  rand_forest(trees = 1000)%>%
  set_engine('ranger')%>%
  set_mode('regression')

episode_wf<- workflow()%>%
  add_recipe(episode_rec)%>%
  add_model(episode_spec)


```

2. Fit model

```{r}
control_preds <- control_resamples(save_pred = TRUE)

episode_results <- fit_resamples(episode_wf,
                                 resamples = episode_folds,
                                 control= control_preds)

episode_results %>% 
  collect_metrics()


episode_results %>% 
  unnest(.predictions)%>%
  ggplot(aes(.pred,rating, color = id ))+geom_point()

episode_last_fit <- last_fit(episode_wf,episode_split)
episode_final_wf <- extract_workflow(episode_last_fit)


episode_final_wf %>% 
  augment(episode_test)%>%
  ggplot(aes(.pred,rating))+geom_point()

```


### Lets try including other features i.e. writer, director and type 
- Using the text data and tf-idf for this data, we can a marginal improvement 
- Preditions also look slightly better on test data 

```{r}

library(tidytext)
data("stop_words")

# add other text columns in the data set 
episodes_clean_new <-
episodes_joined %>% 
  select(episode_number,season_number,episode_title,uk_viewers,rating,duration,writer,director,type)%>%
  drop_na()


# calculate tf-idf for the text fields and create a tf-idf feature matrix 
episode_tfidf <- episodes_clean_new %>%
  mutate(text_col = paste(episode_title,writer,director,type))%>%
  mutate(season_episode = paste(season_number,episode_number))%>%
  select(season_episode,text_col)%>%
  unnest_tokens(.,word,input = text_col)%>%
  anti_join(stop_words)%>%
  count(season_episode,word, sort=TRUE)%>%
  bind_tf_idf(season_episode,word,n)%>%
  pivot_wider(names_from = word,values_from = tf_idf,values_fill = 0)

episode_tfidf_joined <- episode_tfidf %>% 
  select(-c(n,tf,idf))%>%
  left_join(.,episodes_clean_new %>% 
              mutate(season_episode = paste(episode_number,season_number))%>%
              select(season_episode,uk_viewers,rating,duration),
            by = c('season_episode'))%>%
  drop_na()


# create train-test data split on this new data and train model on the new data & recipe 
episode_split_new <- initial_split(episode_tfidf_joined)

episode_train_new <- training(episode_split_new)
episode_test_new <- testing (episode_split_new)

episode_train_new %>% 
  colnames()

episode_folds_new <- vfold_cv(episode_train_new)
episode_folds_new


episode_rec_new <- recipe(rating ~ .,data = episode_train_new)%>%
  step_rm(season_episode)

episode_rec_new %>% prep()%>% bake(new_data = NULL)%>%
  view()



episode_spec <-
  rand_forest(trees = 1000)%>%
  set_engine('ranger')%>%
  set_mode('regression')

episode_wf_new<- workflow()%>%
  add_recipe(episode_rec_new)%>%
  add_model(episode_spec)

control_preds <- control_resamples(save_pred = TRUE)

episode_results_new <- fit_resamples(episode_wf_new,
                                 resamples = episode_folds_new,
                                 control= control_preds)


episode_results_new %>% 
  collect_metrics()

episode_results_new %>% 
  unnest(.predictions)%>%
  ggplot(aes(.pred,rating, color = id ))+geom_point()

episode_last_fit_new <- last_fit(episode_wf_new,episode_split_new)
episode_final_wf_new <- extract_workflow(episode_last_fit_new)


episode_final_wf_new%>% 
  augment(episode_test_new)%>%
  ggplot(aes(.pred,rating))+geom_point()




```





