---
title: "tidytuesday"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(lubridate)


tt <- tidytuesdayR::tt_load('2021-05-25')

tt

drivers <- tt$drivers


world_records <- tt$records%>%
  mutate(date = ymd(date))%>%
  mutate(year = year(date))



drivers

world_records %>% view()


```


```{r}

world_records %>% 
  count(track,year,sort=T)%>%
  ggplot(aes(year,n))+geom_line()+facet_wrap(~track)+
  labs(x = 'Year',
       y ='No of records',
       title = "How records evolved over time ? ",
       subtitle = "No of new records were higher when the game was launched and declined after")



world_records %>% 
  count(track,sort=T)%>%
  mutate(track = fct_reorder(track,n))%>%
  ggplot(aes(n,track))+geom_col()+
  labs(x = 'Number of records',
       y ='Tracks',
       title = "Tracks with most records")



world_records %>% 
  group_by(track)%>%
  summarise(lowest_time = min(time),
            lowest_year = year[which.min(time)])%>%
  mutate(track = fct_rev(fct_reorder(track,lowest_time)))%>%
  ggplot(aes(lowest_time,track))+geom_col()+geom_text(aes(label=lowest_year,hjust = -1))+
  expand_limits(x = c(0,75))+
  labs(x= "Time in seconds",
       y= "Track",
       title = "Lowest time on each track with year of the record")


world_records %>% 
  group_by(track)%>%
  summarise(lowest_time = min(time),
            highest_time = max(time),
            lowest_year = year[which.min(time)],
            highest_year = year[which.max(time)])%>%
  mutate(imp_pct = highest_time - lowest_time)%>%
  mutate(track = fct_reorder(track,imp_pct))%>%
  ggplot(aes(imp_pct,track))+geom_col()+
  labs(x = "Improvement in record in Seconds",
       y = "Track",
       title = "Improvements in Records for each track")

world_records %>% 
  count(track,shortcut,sort=T)%>%
  filter(shortcut == 'Yes')%>%
  mutate(track = fct_reorder(track,n))%>%
  ggplot(aes(n,track))+geom_col()+
  labs(x = 'Number of records',
       y ='Tracks',
       title = "Tracks with most records with shortcuts")


world_records %>%
  mutate(is_shortcut_discovered = ifelse(shortcut == 'Yes',TRUE,FALSE))%>%
  group_by(track)%>%
  mutate(shortcut_discovered = ifelse(sum(is_shortcut_discovered)>0,"Yes","No"))%>%
  group_by(track,shortcut_discovered)%>%
  summarise(shortcut_year = min(year))%>%
  mutate(shortcut_year = ifelse(shortcut_discovered == 'No',NA,shortcut_year))

# All shortcuts were discovered in 1997, for 4 tracks the shortcuts are not discovered yet

  
world_records%>%
  mutate(is_shortcut_discovered = ifelse(shortcut == 'Yes',TRUE,FALSE))%>%
  group_by(track)%>%
  mutate(shortcut_discovered = ifelse(sum(is_shortcut_discovered)>0,"Yes","No"))%>%
  filter(shortcut_discovered == 'Yes')%>%
  group_by(track,shortcut)%>%
  summarise(min_time = min(time))%>%
  spread(key = shortcut,value=min_time)%>%
  ungroup()%>%
  mutate(time_diff = No - Yes)%>%
  mutate(track = fct_reorder(track,time_diff))%>%
  ggplot(aes(time_diff,track))+geom_col()+
  labs(x ="Time difference between lowest time with and without shortcut",
       y= "Track",
       title = "Track wise time difference between records with and without shortcuts")


world_records %>% 
  group_by(track)%>% 
  summarise(max_duration = max(record_duration))%>%
  left_join(.,world_records %>% select(track,record_duration,player,year),
            by = c('track'='track','max_duration'='record_duration'))%>%
  unique()%>%
  ungroup()%>%
  mutate(track = fct_reorder(track,max_duration))%>%
  ggplot(aes(max_duration,track))+geom_col()+
  labs(x = "Max duration of record",
       y="Track",
       title = "Longest standing world record for each track with or without shortcut")

world_records%>% 
  count(player,sort=T)%>%
  mutate(player = fct_reorder(player,n))%>%
  top_n(25)%>%
  ggplot(aes(n,player))+geom_col()+
  labs(x = "No of records",
       y="Player name",
       title = "Players with max world records")

world_records %>% 
  group_by(player)%>%
  summarise(year=max(year))%>%
  arrange(desc(year))
# Recent players list


world_records %>% 
  group_by(track,system_played,shortcut)%>%
  summarise(record_time= min (time))%>%
  ungroup()%>%
  mutate(track = fct_reorder(track,record_time))%>%
  ggplot(aes(record_time,track,fill=system_played))+geom_col(position='dodge')+facet_wrap(~shortcut)+
  labs(x ='Record time',
       y='Track',
       fill='System Played',
       title = "Record timings for each track system wise with and without shortcuts")


```

