---
title: "tidytuesday_superbowl"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r }
library(tidytuesdayR)
library(tidyverse)

tt <- tidytuesdayR::tt_load('2021-03-02')

youtube <- tt$youtube

youtube %>% 
  count(brand)%>%
  mutate(brand = fct_reorder(brand,n))%>%
  ggplot(aes(n,brand,fill=brand))+geom_col()+
  theme(legend.position = 'NULL')+
  labs(x = "Number of ads over the years",
       y = "Brand name",
       title = "Brands with most Superbowl ads")

```

```{r}
youtube %>% 
  count(brand,year)%>%
  mutate(brand=fct_reorder(brand,n))%>%
  ggplot(aes(year,n,fill=brand))+geom_col()+
  labs(x = "Year",
       y = "Count of ads",
       title = "Break up of ads by brands over the years")
```

```{r}
youtube %>% 
  filter(!is.na(view_count))%>%
  mutate(brand=fct_reorder(brand,view_count,sum))%>%
  ggplot(aes(view_count,brand))+geom_col()


youtube %>% 
  filter(!is.na(view_count))%>%
  #mutate(brand=fct_reorder(brand,view_count,sum))%>%
  ggplot(aes(year,view_count))+geom_col()

youtube %>% 
  filter(year == '2012')%>%View()



```

