---
title: "tidytuesday_us_broadband"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(tidytuesdayR)
library(tidyverse)
library(tidycensus)
library(readxl)

```

```{r}

tt <- tidytuesdayR::tt_load('2021-05-11')

tt


broadband <- tt$broadband%>%
  janitor::clean_names()%>%
  rename(state = st)%>%
  mutate(state = state.name[match(state,state.abb)],
         broadband_availability_per_fcc = parse_number(broadband_availability_per_fcc,na='-'),
         broadband_usage = parse_number(broadband_usage,na='-'))
  


broadband_zip <- tt$broadband_zip %>% 
  janitor::clean_names()%>%
  rename(state = st)%>%
  mutate(state = state.name[match(state,state.abb)])
         #broadband_availability_per_fcc = parse_number(broadband_availability_per_fcc,na='-'),
         #broadband_usage = parse_number(broadband_usage,na='-'))

county_population <- read_excel("./co-est2019-annres.xlsx",skip = 3)%>%
  select(county = '...1',population_2017='2017')%>%
  separate(county,c('county_name','state'),sep= ', ')%>%
  #select(-state)%>%
  mutate(county_name = str_remove(county_name,"^\\."))


broadband %>% 
  count(state,sort= TRUE) %>% 
  mutate(state = fct_reorder(state, n))%>%
  top_n(25)%>%
  ggplot(aes(n,state))+geom_col()+
  labs(x = "Number of Counties",
       y = "State",
       title = "No of counties per state")


```


```{r}
broadband_population <- broadband %>% 
  inner_join(county_population,by = c('county_name','state'))%>%
  arrange(desc(population_2017))

broadband_population %>% 
  arrange(desc(population_2017))%>%
  head(25)%>%
  mutate(county_name = fct_reorder(county_name,population_2017))%>%
  ggplot(aes(population_2017,county_name))+geom_col()


broadband_population %>% 
  arrange(desc(population_2017))%>%
  head(40)%>%
  mutate(county_name = fct_reorder(county_name,broadband_availability_per_fcc))%>%
  ggplot(aes(broadband_availability_per_fcc,county_name))+geom_point()+
  scale_x_continuous(labels = scales::percent_format())+
  labs(x = "Broadband availability",
       y= "County name",
       title = "Counties with high broadband availability")




broadband_population %>% 
  arrange(desc(population_2017))%>%
  head(200)%>%
  mutate(county_name = fct_reorder(county_name,broadband_availability_per_fcc))%>%
  ggplot(aes(population_2017,broadband_availability_per_fcc))+geom_point()+
  geom_text(aes(label=county_name),check_overlap = TRUE,hjust=1,vjust =1)+
  scale_y_continuous(labels = scales::percent_format())+
  scale_x_log10(labels = scales::comma_format())+
  expand_limits(x=200000)+
  labs(x = "County population",
       y= "Broadband availability",
       title = "Broadband availabiltiy, population wise")



```

